export interface Major {
  code: string;
  name: string;
  campus: "H1" | "H2";
}

export const MAJORS: Major[] = [
  // ── 서울캠퍼스 (H1) ──────────────────────────────────────────────
  { code: "A4AB2", name: "Business & AI 전공", campus: "H1" },
  { code: "A1CG1", name: "ELLT학과", campus: "H1" },
  { code: "AAQ01", name: "EU전공", campus: "H1" },
  { code: "AAMB1", name: "FATI전공", campus: "H1" },
  { code: "A5A", name: "KFL학부", campus: "H1" },
  { code: "A0A01", name: "Language & AI융합전공", campus: "H1" },
  { code: "AKAA1", name: "Language & Diplomacy전공", campus: "H1" },
  { code: "AKA", name: "Language & Diplomacy학부", campus: "H1" },
  { code: "A2AA1", name: "Language & Trade전공", campus: "H1" },
  { code: "A2A", name: "Language & Trade학부", campus: "H1" },
  { code: "A0B01", name: "Social Science & AI융합전공", campus: "H1" },
  { code: "ALAA1", name: "경영학전공", campus: "H1" },
  { code: "AEC", name: "경제학부", campus: "H1" },
  { code: "AECA1", name: "경제학전공", campus: "H1" },
  { code: "ACDD1", name: "광고·PR·브랜딩전공", campus: "H1" },
  { code: "AFF01", name: "교육학", campus: "H1" },
  { code: "ACAI1", name: "국가리더전공", campus: "H1" },
  { code: "AEAA1", name: "국제통상학과", campus: "H1" },
  { code: "AGA", name: "국제학부", campus: "H1" },
  { code: "AGAA1", name: "국제학전공", campus: "H1" },
  { code: "AAH01", name: "네덜란드어과", campus: "H1" },
  { code: "AAD01", name: "노어과", campus: "H1" },
  { code: "AAC01", name: "독일어과", campus: "H1" },
  { code: "ABP02", name: "동북아외교통상전공", campus: "H1" },
  { code: "ABC01", name: "말레이.인도네시아어과", campus: "H1" },
  { code: "ABJ01", name: "몽골어과", campus: "H1" },
  { code: "ANDD2", name: "문화콘텐츠학전공", campus: "H1" },
  { code: "ACD", name: "미디어커뮤니케이션학부", campus: "H1" },
  { code: "ACDE1", name: "방송·영상·뉴미디어전공", campus: "H1" },
  { code: "ABF01", name: "베트남어과", campus: "H1" },
  { code: "AAP01", name: "브릭스전공", campus: "H1" },
  { code: "ANDB2", name: "사학과", campus: "H1" },
  { code: "A4A04", name: "상담·UX심리전공", campus: "H1" },
  { code: "AANA1", name: "세계문화예술경영전공", campus: "H1" },
  { code: "AAI01", name: "스칸디나비아어과", campus: "H1" },
  { code: "AAE01", name: "스페인어과", campus: "H1" },
  { code: "ABD01", name: "아랍어과", campus: "H1" },
  { code: "ACDA1", name: "언론·정보전공", campus: "H1" },
  { code: "ANDC2", name: "언어인지과학과", campus: "H1" },
  { code: "A1CD1", name: "영미문학·문화학과", campus: "H1" },
  { code: "AFA01", name: "영어교육과", campus: "H1" },
  { code: "A1CE1", name: "영어통번역학과", campus: "H1" },
  { code: "AFJ02", name: "외국어교육학부(독일어교육전공)", campus: "H1" },
  { code: "AFJ03", name: "외국어교육학부(중국어교육전공)", campus: "H1" },
  { code: "AFJ01", name: "외국어교육학부(프랑스어교육전공)", campus: "H1" },
  { code: "A5A01", name: "외국어로서의한국어교육전공", campus: "H1" },
  { code: "A5A02", name: "외국어로서의한국어통번역전공", campus: "H1" },
  { code: "A4AB1", name: "융복합소프트웨어전공", campus: "H1" },
  { code: "AJDA1", name: "융합일본지역전공", campus: "H1" },
  { code: "AJD", name: "융합일본지역학부", campus: "H1" },
  { code: "AAF01", name: "이탈리아어과", campus: "H1" },
  { code: "ABG01", name: "인도어과", campus: "H1" },
  { code: "AJCA1", name: "일본언어문화전공", campus: "H1" },
  { code: "AJC", name: "일본언어문화학부", campus: "H1" },
  { code: "ACBA1", name: "정치외교학과", campus: "H1" },
  { code: "AICA1", name: "중국언어문화전공", campus: "H1" },
  { code: "AIC", name: "중국언어문화학부", campus: "H1" },
  { code: "AIDA1", name: "중국외교통상전공", campus: "H1" },
  { code: "AID", name: "중국외교통상학부", campus: "H1" },
  { code: "AICA2", name: "차이나데이터큐레이션전공", campus: "H1" },
  { code: "ANDA2", name: "철학과", campus: "H1" },
  { code: "ABE01", name: "태국학과", campus: "H1" },
  { code: "ABH11", name: "튀르키예·아제르바이잔학과", campus: "H1" },
  { code: "ABI01", name: "페르시아어·이란학과", campus: "H1" },
  { code: "AAK01", name: "포르투갈어과", campus: "H1" },
  { code: "AAMC1", name: "프랑스·EU전공", campus: "H1" },
  { code: "AAM", name: "프랑스어학부", campus: "H1" },
  { code: "AAMA1", name: "프랑스응용어문학전공", campus: "H1" },
  { code: "AFD01", name: "한국어교육과", campus: "H1" },
  { code: "ACBB1", name: "행정학과", campus: "H1" },

  // ── 글로벌캠퍼스 (H2) ────────────────────────────────────────────
  { code: "A9A01", name: "AI데이터융합전공", campus: "H2" },
  { code: "A4BA3", name: "AI융합전공(Software&AI)", campus: "H2" },
  { code: "A4BB1", name: "Business & AI 전공", campus: "H2" },
  { code: "A9B01", name: "Finance & AI융합전공", campus: "H2" },
  { code: "ARDA1", name: "Global Business & Technology전공", campus: "H2" },
  { code: "A6A92", name: "ICT&AI세부모듈", campus: "H2" },
  { code: "AO1D2", name: "TESOL영어학전공", campus: "H2" },
  { code: "A6A90", name: "게임한류문화산업세부모듈", campus: "H2" },
  { code: "ATZ", name: "공과대학(공통)", campus: "H2" },
  { code: "ACDD1", name: "광고·PR·브랜딩전공", campus: "H2" },
  { code: "AFF01", name: "교육학", campus: "H2" },
  { code: "ACAH1", name: "국가리더전공(글로벌)", campus: "H2" },
  { code: "ARCA1", name: "국제금융학과", campus: "H2" },
  { code: "APH02", name: "그리스‧불가리아학과", campus: "H2" },
  { code: "AXB03", name: "글로벌e스포츠매니지먼트전공", campus: "H2" },
  { code: "AXB02", name: "글로벌스포츠산업전공", campus: "H2" },
  { code: "AXB", name: "글로벌스포츠산업학부", campus: "H2" },
  { code: "AMAA1", name: "기후변화융합전공", campus: "H2" },
  { code: "APK03", name: "남아프리카어전공", campus: "H2" },
  { code: "AOC02", name: "독일어통번역학과", campus: "H2" },
  { code: "APK01", name: "동아프리카어전공", campus: "H2" },
  { code: "AXC", name: "디지털콘텐츠학부", campus: "H2" },
  { code: "AQJ02", name: "러시아학과", campus: "H2" },
  { code: "APC02", name: "루마니아학과", campus: "H2" },
  { code: "AORI2", name: "말레이.인도네시아어통번역학과", campus: "H2" },
  { code: "ANDD2", name: "문화콘텐츠학전공", campus: "H2" },
  { code: "A6A84", name: "미국·영연방전략세부모듈", campus: "H2" },
  { code: "AYAA1", name: "바이오메디컬공학전공", campus: "H2" },
  { code: "ATN", name: "반도체전자공학부(반도체공학전공)", campus: "H2" },
  { code: "ATO", name: "반도체전자공학부(전자공학전공)", campus: "H2" },
  { code: "ACDE1", name: "방송·영상·뉴미디어전공", campus: "H2" },
  { code: "AQ202", name: "브라질학과", campus: "H2" },
  { code: "ANDB2", name: "사학과", campus: "H2" },
  { code: "ATB02", name: "산업경영공학과", campus: "H2" },
  { code: "ASJB2", name: "생명공학과", campus: "H2" },
  { code: "APK02", name: "서아프리카어전공", campus: "H2" },
  { code: "AOSA1", name: "세계문화예술경영전공", campus: "H2" },
  { code: "APF02", name: "세르비아·크로아티아학과", campus: "H2" },
  { code: "ASHA2", name: "수학과", campus: "H2" },
  { code: "AOD02", name: "스페인어통번역학과", campus: "H2" },
  { code: "A6A82", name: "아랍어통번역세부모듈", campus: "H2" },
  { code: "AORG2", name: "아랍어통번역학과", campus: "H2" },
  { code: "APK", name: "아프리카학부", campus: "H2" },
  { code: "ACDA1", name: "언론·정보전공", campus: "H2" },
  { code: "ANDC2", name: "언어인지과학과", campus: "H2" },
  { code: "AO1C2", name: "영미문학·번역전공", campus: "H2" },
  { code: "A6A81", name: "영어통번역세부모듈", campus: "H2" },
  { code: "AO1", name: "영어통번역학부", campus: "H2" },
  { code: "AO1A2", name: "영어통번역학전공", campus: "H2" },
  { code: "APG02", name: "우크라이나학과", campus: "H2" },
  { code: "A6A91", name: "융합비즈니스세부모듈", campus: "H2" },
  { code: "A6A", name: "융합인재학부", campus: "H2" },
  { code: "A6A85", name: "이탈리아·EU전략세부모듈", campus: "H2" },
  { code: "AOE02", name: "이탈리아어통번역학과", campus: "H2" },
  { code: "AQF02", name: "인도학과", campus: "H2" },
  { code: "AORB2", name: "일본어통번역학과", campus: "H2" },
  { code: "ASIB2", name: "전자물리학과", campus: "H2" },
  { code: "ATFB2", name: "정보통신공학과", campus: "H2" },
  { code: "ACBA1", name: "정치외교학과", campus: "H2" },
  { code: "A6A83", name: "중국어통번역세부모듈", campus: "H2" },
  { code: "AORA2", name: "중국어통번역학과", campus: "H2" },
  { code: "A6A86", name: "중동·이슬람전략세부모듈", campus: "H2" },
  { code: "API02", name: "중앙아시아학과", campus: "H2" },
  { code: "A6A87", name: "중화권전략세부모듈", campus: "H2" },
  { code: "ANDA2", name: "철학과", campus: "H2" },
  { code: "APD02", name: "체코·슬로바키아학과", campus: "H2" },
  { code: "ATJA1", name: "컴퓨터공학전공", campus: "H2" },
  { code: "AORE2", name: "태국어통번역학과", campus: "H2" },
  { code: "A6A88", name: "테크노미디어디자인세부모듈", campus: "H2" },
  { code: "ASHB2", name: "통계학과", campus: "H2" },
  { code: "AXD", name: "투어리즘 & 웰니스학부", campus: "H2" },
  { code: "A6A89", name: "패션관광문화산업세부모듈", campus: "H2" },
  { code: "APB02", name: "폴란드학과", campus: "H2" },
  { code: "AQ102", name: "프랑스학과", campus: "H2" },
  { code: "APJ02", name: "한국학과", campus: "H2" },
  { code: "ACBB1", name: "행정학과", campus: "H2" },
  { code: "APE02", name: "헝가리학과", campus: "H2" },
  { code: "ASJC2", name: "화학과", campus: "H2" },
  { code: "ASJA2", name: "환경학과", campus: "H2" },
];
